AWSTemplateFormatVersion: 2010-09-09
Description: Assumable role for cross account VPC peering.
Parameters:
  PeerRequesterAccountId:
    Type: String
Resources:
  peerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Principal:
            AWS: !Ref PeerRequesterAccountId
          Action:
          - 'sts:AssumeRole'
          Effect: Allow
      Path: /
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: 'ec2:AcceptVpcPeeringConnection'
            Resource: '*'
Outputs:

  RoleARN:
    Value: !GetAtt
    - peerRole
    - Arn