AWSTemplateFormatVersion: "2010-09-09"
Description: Automated pipeline to release awscfncli to PIP
Parameters:

  PyPiUsername:
    Type: String
    Description: Parameter name storing PyPi username

  PyPiPassword:
    Type: String
    Description: Parameter name storing PyPi password

  UseTestPyPi:
    Type: String
    Default: "true"
    Description: Use Test PyPi for package upload
    AllowedValues: ["true", "false"]

  InputArtifactPrefix:
    Type: String
    Description: S3 prefix of input code package
    MinLength: 1
    MaxLength: 256

Conditions:

  UseTestPyPiCondition: !Equals [!Ref UseTestPyPi, "true"]

Resources:

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: aws/s3
              SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: aws/s3
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ApprovalTopic:
    Type: AWS::SNS::Topic

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SNSPublish
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                - !Ref ApprovalTopic

  # See https://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-custom-role.html#view-default-service-role-policy
  CodePipelineCannedPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodePipelineCannedPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
            Effect: Allow
            Resource: '*'
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - arn:aws:s3:::codepipeline*
              - arn:aws:s3:::elasticbeanstalk*
          - Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
            Effect: Allow
            Resource: '*'
          - Action:
              - elasticbeanstalk:*
              - autoscaling:*
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeScalingActivities
              - autoscaling:ResumeProcesses
              - autoscaling:SuspendProcesses
              - cloudformation:GetTemplate
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackResources
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - ec2:DescribeInstances
              - ec2:DescribeImages
              - ec2:DescribeAddresses
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
              - ec2:DescribeSecurityGroups
              - ec2:DescribeKeyPairs
              - elasticloadbalancing:DescribeLoadBalancers
              - rds:DescribeDBInstances
              - rds:DescribeOrderableDBInstanceOptions
              - sns:ListSubscriptionsByTopic
            Effect: Allow
            Resource: '*'
          - Action:
              - lambda:invokefunction
              - lambda:listfunctions
            Effect: Allow
            Resource: '*'
          - Action:
              - s3:ListBucket
              - s3:GetBucketPolicy
              - s3:GetObjectAcl
              - s3:PutObjectAcl
              - s3:DeleteObject
            Effect: Allow
            Resource: arn:aws:s3:::elasticbeanstalk*
          - Action:
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:UploadArchive
              - codecommit:GetUploadArchiveStatus
              - codecommit:CancelUploadArchive
            Effect: Allow
            Resource: '*'
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref CodePipelineServiceRole

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:Get*
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${PyPiUsername}
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${PyPiPassword}

  SharedDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectVersion
            Resource:
              - !Join ["/", [ "Fn::GetAtt": ArtifactBucket.Arn , "*" ]]
              - !Join ["/", [ "Fn::GetAtt": SourceBucket.Arn , "*" ]]
      Roles:
        - !Ref CodePipelineServiceRole
        - !Ref CodeBuildServiceRole

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CodePipelineCannedPolicy
      - SharedDeployPolicy
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Name: !Sub ${AWS::StackName}-Pipeline
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RestartExecutionOnUpdate: false
      DisableInboundStageTransitions:
        - StageName: Release
          Reason: "Disabled transition"

      Stages:

        - Name: Source
          Actions:
            - Name: S3Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: !Ref SourceBucket
                S3ObjectKey: !Ref InputArtifactPrefix
                # XXX: not recommended by aws but saves a trail and cw events
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Test
          Actions:
            - Name: UnittestPy38
              RunOrder: 1
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref UnittestProject
                EnvironmentVariables: >
                  [
                    {"name": "PYTHON_VERSION", "value": "3.8", "type": "PLAINTEXT"}
                  ]
              InputArtifacts:
                - Name: SourceArtifact
            - Name: UnittestPy37
              RunOrder: 1
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref UnittestProject
                EnvironmentVariables: >
                  [
                    {"name": "PYTHON_VERSION", "value": "3.7", "type": "PLAINTEXT"}
                  ]
              InputArtifacts:
                - Name: SourceArtifact
            - Name: UnittestPy36
              RunOrder: 1
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref UnittestProject
                EnvironmentVariables: >
                  [
                    {"name": "PYTHON_VERSION", "value": "3.6", "type": "PLAINTEXT"}
                  ]
              InputArtifacts:
                - Name: SourceArtifact
            - Name: SmokingTest
              RunOrder: 2
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref SmokingTestProject
              InputArtifacts:
                - Name: SourceArtifact

        - Name: Release
          Actions:
            - Name: Approve
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:
                NotificationArn: !Ref ApprovalTopic
                ExternalEntityLink: https://github.com/Kotaimen/awscfncli
                CustomData: Upload to PyPi
            - Name: PyPiRelease
              RunOrder: 2
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref ReleaseProject
              InputArtifacts:
                - Name: SourceArtifact

  UnittestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 30
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:3.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: unittest.snippet.yml

  SmokingTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 30
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:3.0
        ComputeType: BUILD_GENERAL1_SMALL
      Source:
        Type: CODEPIPELINE
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: smoking-test.snippet.yml

  ReleaseProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 30
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:3.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
        - Name: TWINE_USERNAME
          Type: PARAMETER_STORE
          Value: !Ref PyPiUsername
        - Name: TWINE_PASSWORD
          Type: PARAMETER_STORE
          Value: !Ref PyPiPassword
        - Name: TWINE_REPOSITORY
          Type: PLAINTEXT
          Value: pypi
        - Name: TWINE_REPOSITORY_URL
          Type: PLAINTEXT
          Value:
            Fn::If:
              - UseTestPyPiCondition
              - https://test.pypi.org/legacy/
              - ""
      Source:
        Type: CODEPIPELINE
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: pypi-release.snippet.yml

Outputs:

  ApprovalTopicArn:
    Description: ARN of approve SNS topic
    Value: !Ref ApprovalTopic
